name: "Build and Push Microservices to Docker Hub"

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.name }}
  DOCKERHUB_PASSWORD: ${{ secrets.password }}
  REPO: kingofpilze  # Docker Hub Namespace

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - course-service
          - user-service
          - feedback-service

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🐳 Create Dockerfile for ${{ matrix.service }}
        working-directory: services/${{ matrix.service }}
        run: |
          cat <<EOF > Dockerfile
          FROM node:18
          WORKDIR /app
          COPY . .
          RUN npm install
          EXPOSE ${PORT:-5000}
          CMD ["node", "index.js"]
          EOF

      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: 🛠 Build Docker Image
        run: |
          docker build -t docker.io/${{ env.REPO }}/${{ matrix.service }}:latest ./services/${{ matrix.service }}

      - name: 🚀 Push to Docker Hub
        run: |
          docker push docker.io/${{ env.REPO }}/${{ matrix.service }}:latest

      - name: 🔍 Scan Image mit Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: docker.io/${{ env.REPO }}/${{ matrix.service }}:latest
